### ISSUE TITLE
How to use ArrayList

### ISSUE THREAD

**Issue by tcqq** [wada811/ViewModel-SavedState-ktx#2]
```
class RegionsViewModel(savedStateHandle: SavedStateHandle): SavedStateViewModel(savedStateHandle) {
    val selectedPositions: ArrayList<Int> by savedStateProperty("key of positions")
}
```

When I call this code: 

`viewModel.selectedPositions.contains(position)`

selectedPositions is empty, how should I fix it? @wada811

**Comment by wada811** [comment]
@tcqq 
This usage is correct.
Please compare sample(a98e1716ec415976d496f977243871570283e2b6) and your code.

**Comment by tcqq** [comment]
Thank you, I understand.
