### ISSUE TITLE
only set the initial value when SavedStateHandle does not contain the key

### ISSUE THREAD

**Issue by samlu** [wada811/ViewModel-SavedState-ktx#4]
In SavedStateHandles.kt, you should only assign initialValue to this[it] when the SavedStateHandle does not contain the key; otherwise, the key/value of SavedStateAdapter will be re-initialized when the property provider is re-created.

**old**
```
this[it] = initialValue
```

**should be changed as**
```
if (!this.contains(it))
  this[it] = initialValue
```

**Comment by wada811** [comment]
Thank you for using and contributing this library. To understand the problem correctly, I want to ask you a question.

### When the property provider is re-created

I thought the property provider is created only once when ViewModel is created. However, I just realized that Activity is killed by OS, and the property provider is re-created. Is this right?

### The property provider's behavior will be changed

The value is also initialized by Intent or Bundle. If the value is initialized by Intent or Bundle, the property provider can't initialize value by `initialValue`. But, I think that the property provider should not initialize but set default value. I'll change it. Is it ok for you?

**Comment by samlu** [comment]
Yes, Android kills the background process (https://developer.android.com/guide/components/activities/activity-lifecycle#asem) and restores Activity to the last state. 

In this case, the property provider is re-created (due to the whole process was killed) but will be initialized with the saveInstanceState bundle. That's why we should first check if the key exists before assigning initialValue to it.

**Comment by wada811** [comment]
Thank you for your answer.
This problem is fixed in 2.3.0-alpha01.

**Comment by Dolognio** [comment]
I think the solution should be 
`if (!this.contains(it))
  this[it] = adapter.toSavedState(initialValue)`
in case an adapter is used. Otherwise we get an exception "java.lang.IllegalArgumentException: Can't put value with type class x.y.z into saved state"

**Comment by wada811** [comment]
@Dolognio 
Thank you for your comment.
This problem is fixed in 2.3.0-beta01.

**Comment by samlu** [comment]
The following function should have the same issue but not get fixed:

fun <TValue, TState> SavedStateHandle.property(adapter: SavedStateAdapter<TValue, TState>, defaultValue: TValue): ReadWritePropertyProvider<ViewModel, TValue>

**Comment by wada811** [comment]
oh..., I missed it.
@samlu thank you for your report.
