### ISSUE TITLE
2.3.0-beta01: targetSdkVersion が指定されていない

### ISSUE THREAD

**Issue by irgaly** [wada811/ViewModel-SavedState-ktx#9]
ViewModel-SavedState-ktx を依存関係に追加したところ、
ビルド後のアプリに `android.permission.READ_PHONE_STATE` が追加されました。

Google Play Services を利用している場合に、利用しているライブラリに targetSdkVersion を指定していないものがあると、この権限が追加されるようです。

https://qiita.com/takahirom/items/cb9865b287dd6bab1007

AndroidManifest Merger に以下のログが出力されているようでした。

```
Merging Log Implied from the app main manifest (this file), line 1; reason: com.wada811.viewmodelsavedstate has a targetSdkVersion < 4
```

**Comment by wada811** [comment]
報告ありがとうございますー！
ViewModel-SavedState-ktx のバージョンは `2.3.0-beta01` でしょうか？
もしその場合は `2.3.0-rc01` をお試しいただけると嬉しいですー！

**Comment by irgaly** [comment]
2.3.0-beta01を使っていました。
2.3.0-rc01を試したところminSdkVersionが指定され、android.permission.READ_PHONE_STATE も消えていることを確認しました。
ありがとうございます！

**Comment by wada811** [comment]
ありがとうございます！
お手数おかけしてすみません！
解決して良かったですー！
